/**
 * TOC (Table of Contents) file generator for FLOW folders.
 *
 * Creates "0. TOC.md" files in specified FLOW folders with
 * either a static file listing or DataView query blocks.
 */

import { Notice, TFile, TFolder, Vault } from "obsidian";
import { FlowFolderMap, FlowRole, FLOW_ROLE_ORDER } from "../../types";
import { findExistingFlowFolder } from "../../core/folder-manager";

const TOC_FILENAME = "0. TOC.md";

/**
 * Generate TOC files for the specified FLOW roles.
 *
 * @param vault The Obsidian vault
 * @param folderMap Current folder name mapping
 * @param roles Which roles to generate TOC for
 * @param useDataView Whether to include DataView queries
 * @returns Number of TOC files created/updated
 */
export async function generateTOCFiles(
	vault: Vault,
	folderMap: FlowFolderMap,
	roles: FlowRole[],
	useDataView: boolean
): Promise<number> {
	let count = 0;

	for (const role of roles) {
		const folderName = folderMap[role];
		const folder = findExistingFlowFolder(vault, folderName);

		if (!folder) {
			console.warn(`[FLOW TOC] Folder "${folderName}" not found, skipping.`);
			continue;
		}

		const tocPath = `${folder.path}/${TOC_FILENAME}`;
		const content = buildTOCContent(folder.name, folder.path, role, vault, useDataView);

		const existing = vault.getAbstractFileByPath(tocPath);
		if (existing && existing instanceof TFile) {
			await vault.modify(existing, content);
		} else {
			await vault.create(tocPath, content);
		}

		count++;
	}

	return count;
}

/**
 * Build the markdown content for a TOC file.
 */
function buildTOCContent(
	folderName: string,
	folderPath: string,
	role: FlowRole,
	vault: Vault,
	useDataView: boolean
): string {
	const roleLabel = role.charAt(0).toUpperCase() + role.slice(1);

	const lines: string[] = [
		`---`,
		`tags:`,
		`  - flow/toc`,
		`created: ${new Date().toISOString().split("T")[0]}`,
		`---`,
		``,
		`# ${folderName}`,
		``,
		`> [!info] Auto-generated by FLOW plugin`,
		`> This file is automatically maintained. Manual edits may be overwritten.`,
		``,
	];

	if (useDataView) {
		// DataView dynamic query
		lines.push(
			`## Notes`,
			``,
			"```dataview",
			`TABLE WITHOUT ID`,
			`  file.link AS "Note",`,
			`  file.cday AS "Created",`,
			`  file.mday AS "Modified"`,
			`FROM "${folderPath}"`,
			`WHERE file.name != "0. TOC"`,
			`SORT file.cday DESC`,
			"```",
			``
		);
	} else {
		// Static file listing
		const folder = vault.getAbstractFileByPath(folderPath);
		if (folder && folder instanceof TFolder) {
			const files = folder.children
				.filter(
					(f): f is TFile =>
						f instanceof TFile &&
						f.extension === "md" &&
						f.name !== TOC_FILENAME
				)
				.sort((a, b) => b.stat.ctime - a.stat.ctime);

			lines.push(`## Notes (${files.length})`, ``);

			if (files.length === 0) {
				lines.push(`*No notes in this folder yet.*`, ``);
			} else {
				for (const file of files) {
					const dateStr = new Date(file.stat.ctime)
						.toISOString()
						.split("T")[0];
					lines.push(`- [[${file.basename}]] — ${dateStr}`);
				}
				lines.push(``);
			}
		}
	}

	return lines.join("\n");
}

/**
 * Get all roles that have existing folders in the vault.
 */
export function getExistingFlowRoles(
	vault: Vault,
	folderMap: FlowFolderMap
): FlowRole[] {
	return FLOW_ROLE_ORDER.filter((role) => {
		return !!findExistingFlowFolder(vault, folderMap[role]);
	});
}
